spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: mamt4real
    password: special
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  ephyto:
    secret: the_secret_token_for_ephyto
    clientId: the_client_id_for_ephyto
